---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: paragon-robotics-linux
# description will be included in the image's metadata
description: A custom Linux image for Paragon Robotics, based on Aurora DX.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: latest # You can pin to a specific version of Fedora as well

platforms:
  - linux/amd64

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - https://cli.github.com/packages/rpm/gh-cli.repo
      copr:
        - lihaohong/forgejo-cli
    install:
      packages:
        - gh
        - forgejo-cli
        - dotnet-sdk-10.0

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - dev.vencord.Vesktop
          - com.vivaldi.Vivaldi
          - com.github.tchx84.Flatseal
          - com.bitwarden.desktop
      - scope: user # Also add Flathub user repo, but no user packages
      
  - type: script
    scripts:
      - setup-dotnet-root.sh
      - setup-onshape-and-browser-hardware-accel.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
